using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

namespace WillGoldstone.Workspaces
{
    /// <summary>
    /// Emits <c>WorkspacesToolbar.Generated.cs</c> with one <see cref="UnityEditor.Toolbars.MainToolbarElementAttribute"/>
    /// per prefab workspace so the Main Toolbar Add (+) menu lists only real workspaces and uses path segments derived from Display Names.
    /// </summary>
    internal static class WorkspacesToolbarCodeGenerator
    {
        private const string GeneratedAssetPath = "Packages/com.willgoldstone.workspaces/Editor/WorkspacesToolbar.Generated.cs";

        internal static void EnsureUpToDate()
        {
            WorkspacesSettings.instance.EnsureDefaults();
            RegenerateIfNeeded(force: false);
        }

        internal static void RegenerateAfterSave()
        {
            WorkspacesSettings.instance.EnsureDefaults();
            RegenerateIfNeeded(force: true);
        }

        private static void RegenerateIfNeeded(bool force)
        {
            var list = WorkspacesSettings.instance.Workspaces.ToList();

            var sb = new StringBuilder(2048);
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// Rebuilt when you click Save in Project Settings > Workspaces (or on editor load if out of date).");
            sb.AppendLine("using UnityEditor.Toolbars;");
            sb.AppendLine();
            sb.AppendLine("namespace WillGoldstone.Workspaces");
            sb.AppendLine("{");
            sb.AppendLine("    internal static partial class WorkspacesToolbar");
            sb.AppendLine("    {");

            var usedSegments = new HashSet<string>();
            for (var i = 0; i < list.Count; i++)
            {
                var def = list[i];
                var segment = WorkspacesToolbarPaths.AllocateUniquePathSegment(def, usedSegments);
                var path = $"Workspaces/{segment}";
                var escapedPath = path.Replace("\\", "\\\\").Replace("\"", "\\\"");
                sb.AppendLine($"        [MainToolbarElement(\"{escapedPath}\", defaultDockPosition = MainToolbarDockPosition.Middle, defaultDockIndex = {i + 1}, menuPriority = {100 + i})]");
                sb.AppendLine($"        public static MainToolbarElement GenToolbar_{i}() => CreatePrefabWorkspaceToolbarElement(\"{def.Id}\");");
                sb.AppendLine();
            }

            if (list.Count == 0)
            {
                sb.AppendLine("        // No prefab workspaces — add rows under Project Settings > Workspaces, then Save.");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var newContent = sb.ToString();
            var fullPath = GetFullPath(GeneratedAssetPath);

            if (!force && File.Exists(fullPath) && File.ReadAllText(fullPath) == newContent)
                return;

            Directory.CreateDirectory(Path.GetDirectoryName(fullPath) ?? ".");
            File.WriteAllText(fullPath, newContent);
            AssetDatabase.ImportAsset(GeneratedAssetPath, ImportAssetOptions.ForceUpdate);
        }

        private static string GetFullPath(string assetPath)
        {
            var projectRoot = Path.GetDirectoryName(UnityEngine.Application.dataPath);
            return Path.GetFullPath(Path.Combine(projectRoot ?? ".", assetPath));
        }
    }

    [InitializeOnLoad]
    internal static class WorkspacesToolbarCodegenBoot
    {
        static WorkspacesToolbarCodegenBoot()
        {
            EditorApplication.delayCall += () => WorkspacesToolbarCodeGenerator.EnsureUpToDate();
        }
    }
}
