// <auto-generated />
// Rebuilt when you click Save in Project Settings > Workspaces (or on editor load if out of date).
using UnityEditor.Toolbars;

namespace WillGoldstone.Workspaces
{
    internal static partial class WorkspacesToolbar
    {
        [MainToolbarElement("Workspaces/Player", defaultDockPosition = MainToolbarDockPosition.Middle, defaultDockIndex = 1, menuPriority = 100)]
        public static MainToolbarElement GenToolbar_0() => CreatePrefabWorkspaceToolbarElement("fe4f970f99a54afb9d779380b56e4128");

        [MainToolbarElement("Workspaces/Enemy", defaultDockPosition = MainToolbarDockPosition.Middle, defaultDockIndex = 2, menuPriority = 101)]
        public static MainToolbarElement GenToolbar_1() => CreatePrefabWorkspaceToolbarElement("56ffc7ed99cc426493c68432d3ac39f0");

        [MainToolbarElement("Workspaces/Landmine", defaultDockPosition = MainToolbarDockPosition.Middle, defaultDockIndex = 3, menuPriority = 102)]
        public static MainToolbarElement GenToolbar_2() => CreatePrefabWorkspaceToolbarElement("9f7bf50608c1478fa931357d509f9288");

        [MainToolbarElement("Workspaces/Tile", defaultDockPosition = MainToolbarDockPosition.Middle, defaultDockIndex = 4, menuPriority = 103)]
        public static MainToolbarElement GenToolbar_3() => CreatePrefabWorkspaceToolbarElement("f6120ecf32dd47bdbe83a634298b4def");

        [MainToolbarElement("Workspaces/Bomb", defaultDockPosition = MainToolbarDockPosition.Middle, defaultDockIndex = 5, menuPriority = 104)]
        public static MainToolbarElement GenToolbar_4() => CreatePrefabWorkspaceToolbarElement("b868d84be7094622a037f8c8c34093fa");

        [MainToolbarElement("Workspaces/Ability_Card", defaultDockPosition = MainToolbarDockPosition.Middle, defaultDockIndex = 6, menuPriority = 105)]
        public static MainToolbarElement GenToolbar_5() => CreatePrefabWorkspaceToolbarElement("3b315835462b40989ef4b65721fa60e3");

    }
}
